### ISSUE TITLE
Bowtie not mapping 100%

### ISSUE THREAD

**Issue by Stakaitis** [BenLangmead/bowtie#130]
**Issue**:
Bowtie does not recognize a 21 nt length sequence, even though it matches the first 20 nt but only has one extra nucleotide at the very end.

**Example**:
_ref.fa_ (without quotes) 
">5P_ath-miR159a_3_2-OMe
TTTGGATTGAAGGGAGCTCT"

_r1.fq_ (without quotes)
"@A01058:221:HLKLTDSX3:4:1101:1045:1016 1:N:0:NATCAG
TTTGGATTGAAGGGAGCTCTA
+
FFFFFFFFFFFFFFFFFFFFF"

**Commands**:
`bowtie-build ref.fa ref`
`bowtie ref r1.fq` (also tried various alignment arguments)

**Report**:
`reads processed: 1`
`reads with at least one reported alignment: 0 (0.00%)`
`reads that failed to align: 1 (100.00%)`
`No alignments`

**Version**:
version 1.2.3 installed by running `conda install -c bioconda bowtie` on mac

**Comment by mschilli87** [comment]
IIRC, unlike Bowtie 2, BWA and many other mappers, Bowtie does *not* soft-clip reads. *I.e.* a missmatch in the beginning/end counts as such. I assume due to the shortness of the sequence, this one mismatch pushes the alignment score below the (default) threshold.

Guessing by the particular length of your read and the sequence name in your example, you might want to have a look at how [miRDeep2](https://github.com/rajewsky-lab/mirdeep2) maps sRNA-seq reads to pre-miRNAs [using Bowtie](https://github.com/rajewsky-lab/mirdeep2/blob/c6440e298795579ad62351bba7aff9cc43c50c68/src/quantifier.pl#L423). :wink: See [here](https://github.com/rajewsky-lab/mirdeep2/blob/c6440e298795579ad62351bba7aff9cc43c50c68/src/quantifier.pl#L76) for its default number of accepted mismatches. Probably you'll have to optimize the parameters further for your use  case of mapping straight to the mature miRNAs.
