### ISSUE TITLE
Interleaved fastq support

### ISSUE THREAD

**Issue by Jirapong** [BenLangmead/bowtie#16]
In BWA, there is a parameter -p to support a single fastq file which is the interleaved fastq (single paired end).

```
e.g. bwa mem -M -t 16 -p ref.fa read.fq > aln.sam
```

How can we use the interleaved fastq with bowtie?

**Comment by val-antonescu** [comment]
bowtie does not have an option for interleaved fastq files. You can use --12, which comes close but it is still not what you want. You will need to process the input fastq file before using it with bowtie to separate pair1 from pair2. This can be done in many ways. IMHO it can be done with not much complexity in one single line. For example:

 ./bowtie myindex -1 <(cat interleaved.fq | awk 'BEGIN{s=0}{if (s==0){print;} if (NR%4==0){s=(s+1)%2;} }') -2 <(cat interleaved.fq | awk 'BEGIN{s=0}{if (s==1){print;} if (NR%4==0){s=(s+1)%2;} }')

**Comment by Jirapong** [comment]
@val-antonescu Yes, in my case. I'm trying to integrate bowtie into the Hadoop Streaming pipeline. It almost work perfectly.

**Comment by fungs** [comment]
The splitting solutions works but I would totally support this feature request because I don't see a great benefit in actually splitting data into two parts if one almost always uses both parts simultaneously. This is awkward in particular when you are working this streams/pipes, not files. For instance, with most shells it is not so easy to specify multiple non-linear streams/pipes. And the implementation of the file parser is not more than a few lines in most programming languages.

**Comment by BenLangmead** [comment]
Update: this has been implemented in Bowtie 2 and we plan to move it over to Bowtie in the future, though probably not in the imminent 1.2.1 release.
