### ISSUE TITLE
pending difficulty with finding long index

### ISSUE THREAD

**Issue by gbottu** [BenLangmead/bowtie#28]
Following an earlier issue report the line
idx_basename = arguments[-1]
in the script "bowtie" was changed into
idx_basename = arguments[-2]
This however does not solve the problem, because a command line is like
bowtie [options]\* <ebwt> {-1 <m1> -2 <m2> | --12 <r> | <s>} [<hit>]
Hence the index can have a position index anything from -1 to -5.

**Comment by mluypaert** [comment]
This is still an issue (in the current Bowtie 1.1.2). For more details, see the latest comments on this [sourgeforge ticket](https://sourceforge.net/p/bowtie-bio/bugs/331/). 
Can anyone please fix this for good?

**Comment by ch4rr0** [comment]
@mluypaert -- I am working on a fix for this (will reply with ETA). In the meantime if you intend on running bowtie with a large index can you please include the --large-index option. That should resolve the issue in the interim.

**Comment by mluypaert** [comment]
@ch4rr0 
Thanks for the tip (I was aware of it). Before publishing a new release (after fixing this issue), please ensure that #35 (an issue I just created) gets fixed as well. To my opinion, issue #35 is even more urgent than this issue, as there is no easy fix for it (as far as I know) and it probably happens unnoticed with many other users (since bowtie does not report any errors).

**Comment by ch4rr0** [comment]
A fix for this issue was included as part of our most recent release.
