### ISSUE TITLE
invalid fastq files produced using --un

### ISSUE THREAD

**Issue by bwlang** [BenLangmead/bowtie#8]
When I map a sample of reads, I see a small number of fastq entries in the umapped file that do not have a leading @ symbol...

The only odd thing I can think of about this dataset is that it has been adapter trimmed and has some 0 length reads. I removed those 0 length reads and do not see the missing prefix reads.

Reads and the corrupt unmapped reads file can be found at:

https://nebiolabs-my.sharepoint.com/personal/langhorst_neb_com/_layouts/15/guestaccess.aspx?guestaccesstoken=WrkBbCgRVJAXVnxTAVmzpyv9DTdHraI8KfQp7KeSimY%3d&docid=0a458680972664713b9951644f44dab26

Sorry for the terrible link - it seems that github won't take a tgz file attachment (3M)

I tried to map these to rhodo CGA009 - http://www.ncbi.nlm.nih.gov/nuccore/39933080?report=fasta

I think this is a bug.

**Comment by val-antonescu** [comment]
I think this is currently fixed for the next release. I test it on your data and got:
 # reads processed: 124799
 # reads with at least one reported alignment: 122517 (98.17%)
 # reads that failed to align: 2282 (1.83%)

I also noticed a bunch of them being skipped due to being too short.
The un-mapped reads results are different from what you got though. But all of them seem correctly formatted this time.

thank you for reporting this,
Val
